#!/bin/bash

cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-admin
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-api-browser
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-authentication
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-automated-testing
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-bootstrap-installer
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-content-repository
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-core-docs
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-datetime
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-developer-support
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-events
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-kernel
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-lang
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-mail
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-mail-lite
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-messaging
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-reference
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-service-contract
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-subsite
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-tcl
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-templating
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches acs-workflow

cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches ajaxhelper
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches bug-tracker
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches bulk-mail
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches calendar
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches chat
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches cms
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches diagram
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches ecommerce
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches events

cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-big-brother
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-bug-tracker
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-calendar
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-core
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-cost
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-cvs-integration
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-dw-light
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-dynfield
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-exchange-rate
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-expenses
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-filestorage
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-forum
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-ganttproject
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-hr
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-invoices
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-invoices-templates
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-mail-import
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-material
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-notes
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-payments
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-reporting
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-reporting-tutorial
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-search-pg
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-search-pg-files
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-security-update-client
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-simple-survey
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-sysconfig
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-timesheet2
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-timesheet2-invoices
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-timesheet2-task-popup
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-timesheet2-tasks
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-tinytm
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-trans-invoices
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-trans-project-wizard
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-translation
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-update-client
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-wiki
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches intranet-workflow

cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches notifications
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches ref-countries
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches ref-language
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches ref-timezones
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches ref-us-countries
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches ref-us-states
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches ref-us-zipcodes
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches rss-support
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches search
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches simple-survey
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches wiki
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches workflow
cvs -d :pserver:anonymous@berlin.dnsalias.com:/home/cvsroot checkout -r b3-3-patches xml-rpc
