echo /web/projop/packages/acs-admin; cd /web/projop/packages/acs-admin; git pull
echo /web/projop/packages/acs-api-browser; cd /web/projop/packages/acs-api-browser; git pull
echo /web/projop/packages/acs-authentication; cd /web/projop/packages/acs-authentication; git pull
echo /web/projop/packages/acs-automated-testing; cd /web/projop/packages/acs-automated-testing; git pull
echo /web/projop/packages/acs-bootstrap-installer; cd /web/projop/packages/acs-bootstrap-installer; git pull
echo /web/projop/packages/acs-content-repository; cd /web/projop/packages/acs-content-repository; git pull
echo /web/projop/packages/acs-core-docs; cd /web/projop/packages/acs-core-docs; git pull
echo /web/projop/packages/acs-datetime; cd /web/projop/packages/acs-datetime; git pull
echo /web/projop/packages/acs-developer-support; cd /web/projop/packages/acs-developer-support; git pull
echo /web/projop/packages/acs-events; cd /web/projop/packages/acs-events; git pull
echo /web/projop/packages/acs-kernel; cd /web/projop/packages/acs-kernel; git pull
echo /web/projop/packages/acs-lang; cd /web/projop/packages/acs-lang; git pull
echo /web/projop/packages/acs-mail-lite; cd /web/projop/packages/acs-mail-lite; git pull
echo /web/projop/packages/acs-mail; cd /web/projop/packages/acs-mail; git pull
echo /web/projop/packages/acs-messaging; cd /web/projop/packages/acs-messaging; git pull
echo /web/projop/packages/acs-reference; cd /web/projop/packages/acs-reference; git pull
echo /web/projop/packages/acs-service-contract; cd /web/projop/packages/acs-service-contract; git pull
echo /web/projop/packages/acs-subsite; cd /web/projop/packages/acs-subsite; git pull
echo /web/projop/packages/acs-tcl; cd /web/projop/packages/acs-tcl; git pull
echo /web/projop/packages/acs-templating; cd /web/projop/packages/acs-templating; git pull
echo /web/projop/packages/acs-translations; cd /web/projop/packages/acs-translations; git pull
echo /web/projop/packages/acs-workflow; cd /web/projop/packages/acs-workflow; git pull
echo /web/projop/packages/ajaxhelper; cd /web/projop/packages/ajaxhelper; git pull
echo /web/projop/packages/attachments; cd /web/projop/packages/attachments; git pull
echo /web/projop/packages/calendar; cd /web/projop/packages/calendar; git pull
echo /web/projop/packages/categories; cd /web/projop/packages/categories; git pull
echo /web/projop/packages/diagram; cd /web/projop/packages/diagram; git pull
echo /web/projop/packages/file-storage; cd /web/projop/packages/file-storage; git pull
echo /web/projop/packages/general-comments; cd /web/projop/packages/general-comments; git pull
echo /web/projop/packages/intranet-agile; cd /web/projop/packages/intranet-agile; git pull
echo /web/projop/packages/intranet-calendar; cd /web/projop/packages/intranet-calendar; git pull
echo /web/projop/packages/intranet-confdb; cd /web/projop/packages/intranet-confdb; git pull
echo /web/projop/packages/intranet-core; cd /web/projop/packages/intranet-core; git pull
echo /web/projop/packages/intranet-cost; cd /web/projop/packages/intranet-cost; git pull
echo /web/projop/packages/intranet-crm-opportunities; cd /web/projop/packages/intranet-crm-opportunities; git pull
echo /web/projop/packages/intranet-csv-import; cd /web/projop/packages/intranet-csv-import; git pull
echo /web/projop/packages/intranet-cvs-integration; cd /web/projop/packages/intranet-cvs-integration; git pull
echo /web/projop/packages/intranet-demo-data; cd /web/projop/packages/intranet-demo-data; git pull
echo /web/projop/packages/intranet-department-planner; cd /web/projop/packages/intranet-department-planner; git pull
echo /web/projop/packages/intranet-dw-light; cd /web/projop/packages/intranet-dw-light; git pull
echo /web/projop/packages/intranet-dynfield; cd /web/projop/packages/intranet-dynfield; git pull
echo /web/projop/packages/intranet-earned-value-management; cd /web/projop/packages/intranet-earned-value-management; git pull
echo /web/projop/packages/intranet-exchange-rate; cd /web/projop/packages/intranet-exchange-rate; git pull
echo /web/projop/packages/intranet-expenses-workflow; cd /web/projop/packages/intranet-expenses-workflow; git pull
echo /web/projop/packages/intranet-expenses; cd /web/projop/packages/intranet-expenses; git pull
echo /web/projop/packages/intranet-filestorage; cd /web/projop/packages/intranet-filestorage; git pull
echo /web/projop/packages/intranet-forum; cd /web/projop/packages/intranet-forum; git pull
echo /web/projop/packages/intranet-freelance; cd /web/projop/packages/intranet-freelance; git pull
echo /web/projop/packages/intranet-gantt-editor; cd /web/projop/packages/intranet-gantt-editor; git pull
echo /web/projop/packages/intranet-ganttproject; cd /web/projop/packages/intranet-ganttproject; git pull
echo /web/projop/packages/intranet-helpdesk; cd /web/projop/packages/intranet-helpdesk; git pull
echo /web/projop/packages/intranet-hr; cd /web/projop/packages/intranet-hr; git pull
echo /web/projop/packages/intranet-idea-management; cd /web/projop/packages/intranet-idea-management; git pull
echo /web/projop/packages/intranet-invoices-templates; cd /web/projop/packages/intranet-invoices-templates; git pull
echo /web/projop/packages/intranet-invoices; cd /web/projop/packages/intranet-invoices; git pull
echo /web/projop/packages/intranet-jira; cd /web/projop/packages/intranet-jira; git pull
echo /web/projop/packages/intranet-mail-import; cd /web/projop/packages/intranet-mail-import; git pull
echo /web/projop/packages/intranet-material; cd /web/projop/packages/intranet-material; git pull
echo /web/projop/packages/intranet-milestone; cd /web/projop/packages/intranet-milestone; git pull
echo /web/projop/packages/intranet-nagios; cd /web/projop/packages/intranet-nagios; git pull
echo /web/projop/packages/intranet-notes; cd /web/projop/packages/intranet-notes; git pull
echo /web/projop/packages/intranet-payments; cd /web/projop/packages/intranet-payments; git pull
echo /web/projop/packages/intranet-planning; cd /web/projop/packages/intranet-planning; git pull
echo /web/projop/packages/intranet-portfolio-management; cd /web/projop/packages/intranet-portfolio-management; git pull
echo /web/projop/packages/intranet-portfolio-planner; cd /web/projop/packages/intranet-portfolio-planner; git pull
echo /web/projop/packages/intranet-project-scoring; cd /web/projop/packages/intranet-project-scoring; git pull
echo /web/projop/packages/intranet-release-mgmt; cd /web/projop/packages/intranet-release-mgmt; git pull
echo /web/projop/packages/intranet-reporting-dashboard; cd /web/projop/packages/intranet-reporting-dashboard; git pull
echo /web/projop/packages/intranet-reporting-finance; cd /web/projop/packages/intranet-reporting-finance; git pull
echo /web/projop/packages/intranet-reporting-indicators; cd /web/projop/packages/intranet-reporting-indicators; git pull
echo /web/projop/packages/intranet-reporting-openoffice; cd /web/projop/packages/intranet-reporting-openoffice; git pull
echo /web/projop/packages/intranet-reporting-tutorial; cd /web/projop/packages/intranet-reporting-tutorial; git pull
echo /web/projop/packages/intranet-reporting; cd /web/projop/packages/intranet-reporting; git pull
echo /web/projop/packages/intranet-resource-management; cd /web/projop/packages/intranet-resource-management; git pull
echo /web/projop/packages/intranet-rest; cd /web/projop/packages/intranet-rest; git pull
echo /web/projop/packages/intranet-riskmanagement; cd /web/projop/packages/intranet-riskmanagement; git pull
echo /web/projop/packages/intranet-rule-engine; cd /web/projop/packages/intranet-rule-engine; git pull
echo /web/projop/packages/intranet-search-pg; cd /web/projop/packages/intranet-search-pg; git pull
echo /web/projop/packages/intranet-security-update-client; cd /web/projop/packages/intranet-security-update-client; git pull
echo /web/projop/packages/intranet-sharepoint; cd /web/projop/packages/intranet-sharepoint; git pull
echo /web/projop/packages/intranet-simple-survey; cd /web/projop/packages/intranet-simple-survey; git pull
echo /web/projop/packages/intranet-sla-management; cd /web/projop/packages/intranet-sla-management; git pull
echo /web/projop/packages/intranet-spam; cd /web/projop/packages/intranet-spam; git pull
echo /web/projop/packages/intranet-sql-selectors; cd /web/projop/packages/intranet-sql-selectors; git pull
echo /web/projop/packages/intranet-sugarcrm; cd /web/projop/packages/intranet-sugarcrm; git pull
echo /web/projop/packages/intranet-sysconfig; cd /web/projop/packages/intranet-sysconfig; git pull
echo /web/projop/packages/intranet-task-management; cd /web/projop/packages/intranet-task-management; git pull
echo /web/projop/packages/intranet-timesheet2-invoices; cd /web/projop/packages/intranet-timesheet2-invoices; git pull
echo /web/projop/packages/intranet-timesheet2-task-popup; cd /web/projop/packages/intranet-timesheet2-task-popup; git pull
echo /web/projop/packages/intranet-timesheet2-tasks; cd /web/projop/packages/intranet-timesheet2-tasks; git pull
echo /web/projop/packages/intranet-timesheet2-workflow; cd /web/projop/packages/intranet-timesheet2-workflow; git pull
echo /web/projop/packages/intranet-timesheet2; cd /web/projop/packages/intranet-timesheet2; git pull
echo /web/projop/packages/intranet-wiki; cd /web/projop/packages/intranet-wiki; git pull
echo /web/projop/packages/intranet-workflow; cd /web/projop/packages/intranet-workflow; git pull
echo /web/projop/packages/intranet-xmlrpc; cd /web/projop/packages/intranet-xmlrpc; git pull
echo /web/projop/packages/mail-tracking; cd /web/projop/packages/mail-tracking; git pull
echo /web/projop/packages/notifications; cd /web/projop/packages/notifications; git pull
echo /web/projop/packages/oacs-dav; cd /web/projop/packages/oacs-dav; git pull
echo /web/projop/packages/openacs-default-theme; cd /web/projop/packages/openacs-default-theme; git pull
echo /web/projop/packages/organizations; cd /web/projop/packages/organizations; git pull
echo /web/projop/packages/postal-address; cd /web/projop/packages/postal-address; git pull
echo /web/projop/packages/ref-countries; cd /web/projop/packages/ref-countries; git pull
echo /web/projop/packages/ref-currency; cd /web/projop/packages/ref-currency; git pull
echo /web/projop/packages/ref-language; cd /web/projop/packages/ref-language; git pull
echo /web/projop/packages/ref-timezones; cd /web/projop/packages/ref-timezones; git pull
echo /web/projop/packages/ref-us-counties; cd /web/projop/packages/ref-us-counties; git pull
echo /web/projop/packages/ref-us-states; cd /web/projop/packages/ref-us-states; git pull
echo /web/projop/packages/ref-us-zipcodes; cd /web/projop/packages/ref-us-zipcodes; git pull
echo /web/projop/packages/rss-support; cd /web/projop/packages/rss-support; git pull
echo /web/projop/packages/search; cd /web/projop/packages/search; git pull
echo /web/projop/packages/sencha-core; cd /web/projop/packages/sencha-core; git pull
echo /web/projop/packages/sencha-extjs-v421; cd /web/projop/packages/sencha-extjs-v421; git pull
echo /web/projop/packages/senchatouch-timesheet; cd /web/projop/packages/senchatouch-timesheet; git pull
echo /web/projop/packages/senchatouch-v242; cd /web/projop/packages/senchatouch-v242; git pull
echo /web/projop/packages/simple-survey; cd /web/projop/packages/simple-survey; git pull
echo /web/projop/packages/wiki; cd /web/projop/packages/wiki; git pull
echo /web/projop/packages/workflow; cd /web/projop/packages/workflow; git pull
echo /web/projop/packages/xml-rpc; cd /web/projop/packages/xml-rpc; git pull
echo /web/projop/packages/xotcl-core; cd /web/projop/packages/xotcl-core; git pull
echo /web/projop/packages/xotcl-request-monitor; cd /web/projop/packages/xotcl-request-monitor; git pull
echo /web/projop/packages/xowiki; cd /web/projop/packages/xowiki; git pull
