#!/bin/bash

git clone https://gitlab.project-open.net/project-open/acs-admin
git clone https://gitlab.project-open.net/project-open/acs-api-browser
git clone https://gitlab.project-open.net/project-open/acs-authentication
git clone https://gitlab.project-open.net/project-open/acs-automated-testing
git clone https://gitlab.project-open.net/project-open/acs-bootstrap-installer
git clone https://gitlab.project-open.net/project-open/acs-content-repository
git clone https://gitlab.project-open.net/project-open/acs-core-docs
git clone https://gitlab.project-open.net/project-open/acs-datetime
git clone https://gitlab.project-open.net/project-open/acs-developer-support
git clone https://gitlab.project-open.net/project-open/acs-events
git clone https://gitlab.project-open.net/project-open/acs-kernel
git clone https://gitlab.project-open.net/project-open/acs-lang
git clone https://gitlab.project-open.net/project-open/acs-lang-server
git clone https://gitlab.project-open.net/project-open/acs-mail
git clone https://gitlab.project-open.net/project-open/acs-mail-lite
git clone https://gitlab.project-open.net/project-open/acs-messaging
git clone https://gitlab.project-open.net/project-open/acs-reference
git clone https://gitlab.project-open.net/project-open/acs-service-contract
git clone https://gitlab.project-open.net/project-open/acs-subsite
git clone https://gitlab.project-open.net/project-open/acs-tcl
git clone https://gitlab.project-open.net/project-open/acs-templating
git clone https://gitlab.project-open.net/project-open/acs-translations
git clone https://gitlab.project-open.net/project-open/acs-workflow
git clone https://gitlab.project-open.net/project-open/ajaxhelper
git clone https://gitlab.project-open.net/project-open/attachments
git clone https://gitlab.project-open.net/project-open/auth-ldap-adldapsearch
git clone https://gitlab.project-open.net/project-open/batch-importer
git clone https://gitlab.project-open.net/project-open/bug-tracker
git clone https://gitlab.project-open.net/project-open/bulk-mail
git clone https://gitlab.project-open.net/project-open/calendar
git clone https://gitlab.project-open.net/project-open/categories
git clone https://gitlab.project-open.net/project-open/cronjob
git clone https://gitlab.project-open.net/project-open/diagram
git clone https://gitlab.project-open.net/project-open/edit-this-page
git clone https://gitlab.project-open.net/project-open/events
git clone https://gitlab.project-open.net/project-open/faq
git clone https://gitlab.project-open.net/project-open/file-storage
git clone https://gitlab.project-open.net/project-open/general-comments
git clone https://gitlab.project-open.net/project-open/intermedia-driver
git clone https://gitlab.project-open.net/project-open/intranet-adrtel-sap
git clone https://gitlab.project-open.net/project-open/intranet-agile
git clone https://gitlab.project-open.net/project-open/intranet-amberjack
git clone https://gitlab.project-open.net/project-open/intranet-asus-server
git clone https://gitlab.project-open.net/project-open/intranet-audit
git clone https://gitlab.project-open.net/project-open/intranet-baseline
git clone https://gitlab.project-open.net/project-open/intranet-big-brother
git clone https://gitlab.project-open.net/project-open/intranet-budget
git clone https://gitlab.project-open.net/project-open/intranet-bug-tracker
git clone https://gitlab.project-open.net/project-open/intranet-calendar
git clone https://gitlab.project-open.net/project-open/intranet-calendar-holidays
git clone https://gitlab.project-open.net/project-open/intranet-confdb
git clone https://gitlab.project-open.net/project-open/intranet-contacts
git clone https://gitlab.project-open.net/project-open/intranet-core
git clone https://gitlab.project-open.net/project-open/intranet-cost
git clone https://gitlab.project-open.net/project-open/intranet-cost-center
git clone https://gitlab.project-open.net/project-open/intranet-crm-opportunities
git clone https://gitlab.project-open.net/project-open/intranet-crm-opportunities-adrtel
git clone https://gitlab.project-open.net/project-open/intranet-crm-software-comparison
git clone https://gitlab.project-open.net/project-open/intranet-crm-tracking
git clone https://gitlab.project-open.net/project-open/intranet-csv-import
git clone https://gitlab.project-open.net/project-open/intranet-cust-adrtel
git clone https://gitlab.project-open.net/project-open/intranet-cust-aec
git clone https://gitlab.project-open.net/project-open/intranet-cust-baselkb
git clone https://gitlab.project-open.net/project-open/intranet-cust-bnef
git clone https://gitlab.project-open.net/project-open/intranet-cust-bubblebridge
git clone https://gitlab.project-open.net/project-open/intranet-cust-bv
git clone https://gitlab.project-open.net/project-open/intranet-cust-cambridge
git clone https://gitlab.project-open.net/project-open/intranet-cust-celonic
git clone https://gitlab.project-open.net/project-open/intranet-cust-champ
git clone https://gitlab.project-open.net/project-open/intranet-cust-conti
git clone https://gitlab.project-open.net/project-open/intranet-cust-cosine
git clone https://gitlab.project-open.net/project-open/intranet-cust-cpdc
git clone https://gitlab.project-open.net/project-open/intranet-cust-csmi
git clone https://gitlab.project-open.net/project-open/intranet-cust-ctubasel
git clone https://gitlab.project-open.net/project-open/intranet-cust-economedic
git clone https://gitlab.project-open.net/project-open/intranet-cust-efficientip
git clone https://gitlab.project-open.net/project-open/intranet-cust-eicom
git clone https://gitlab.project-open.net/project-open/intranet-cust-ekelow
git clone https://gitlab.project-open.net/project-open/intranet-cust-fttx
git clone https://gitlab.project-open.net/project-open/intranet-cust-genedata
git clone https://gitlab.project-open.net/project-open/intranet-cust-haas
git clone https://gitlab.project-open.net/project-open/intranet-cust-hispano
git clone https://gitlab.project-open.net/project-open/intranet-cust-infrax
git clone https://gitlab.project-open.net/project-open/intranet-cust-issa
git clone https://gitlab.project-open.net/project-open/intranet-cust-jago
git clone https://gitlab.project-open.net/project-open/intranet-cust-koernigweber
git clone https://gitlab.project-open.net/project-open/intranet-cust-kpc
git clone https://gitlab.project-open.net/project-open/intranet-cust-laser
git clone https://gitlab.project-open.net/project-open/intranet-cust-lexcelera
git clone https://gitlab.project-open.net/project-open/intranet-cust-lippokwolf
git clone https://gitlab.project-open.net/project-open/intranet-cust-moravia
git clone https://gitlab.project-open.net/project-open/intranet-cust-nest
git clone https://gitlab.project-open.net/project-open/intranet-customer-portal
git clone https://gitlab.project-open.net/project-open/intranet-cust-opi
git clone https://gitlab.project-open.net/project-open/intranet-cust-processa
git clone https://gitlab.project-open.net/project-open/intranet-cust-projop
git clone https://gitlab.project-open.net/project-open/intranet-cust-reinisch
git clone https://gitlab.project-open.net/project-open/intranet-cust-rosetta
git clone https://gitlab.project-open.net/project-open/intranet-cust-santander
git clone https://gitlab.project-open.net/project-open/intranet-cust-seim
git clone https://gitlab.project-open.net/project-open/intranet-cust-semiotic
git clone https://gitlab.project-open.net/project-open/intranet-cust-shi
git clone https://gitlab.project-open.net/project-open/intranet-cust-sjm
git clone https://gitlab.project-open.net/project-open/intranet-cust-solidline
git clone https://gitlab.project-open.net/project-open/intranet-cust-sprylab
git clone https://gitlab.project-open.net/project-open/intranet-cust-tembit
git clone https://gitlab.project-open.net/project-open/intranet-cust-ventum
git clone https://gitlab.project-open.net/project-open/intranet-cust-versia
git clone https://gitlab.project-open.net/project-open/intranet-cust-whp
git clone https://gitlab.project-open.net/project-open/intranet-cust-yada
git clone https://gitlab.project-open.net/project-open/intranet-cvs-integration
git clone https://gitlab.project-open.net/project-open/intranet-demo-data
git clone https://gitlab.project-open.net/project-open/intranet-department-planner
git clone https://gitlab.project-open.net/project-open/intranet-dw-light
git clone https://gitlab.project-open.net/project-open/intranet-dynfield
git clone https://gitlab.project-open.net/project-open/intranet-earned-value-management
git clone https://gitlab.project-open.net/project-open/intranet-employee-evaluation
git clone https://gitlab.project-open.net/project-open/intranet-estimate-to-complete
git clone https://gitlab.project-open.net/project-open/intranet-events
git clone https://gitlab.project-open.net/project-open/intranet-exchange-rate
git clone https://gitlab.project-open.net/project-open/intranet-expenses
git clone https://gitlab.project-open.net/project-open/intranet-expenses-workflow
git clone https://gitlab.project-open.net/project-open/intranet-filestorage
git clone https://gitlab.project-open.net/project-open/intranet-filestorage-size-indicator
git clone https://gitlab.project-open.net/project-open/intranet-forum
git clone https://gitlab.project-open.net/project-open/intranet-freelance
git clone https://gitlab.project-open.net/project-open/intranet-freelance-invoices
git clone https://gitlab.project-open.net/project-open/intranet-freelance-invoices-moravia
git clone https://gitlab.project-open.net/project-open/intranet-freelance-rfqs
git clone https://gitlab.project-open.net/project-open/intranet-freelance-translation
git clone https://gitlab.project-open.net/project-open/intranet-funambol
git clone https://gitlab.project-open.net/project-open/intranet-gantt-editor
git clone https://gitlab.project-open.net/project-open/intranet-ganttproject
git clone https://gitlab.project-open.net/project-open/intranet-general-comments
git clone https://gitlab.project-open.net/project-open/intranet-gtd-dashboard
git clone https://gitlab.project-open.net/project-open/intranet-helpdesk
git clone https://gitlab.project-open.net/project-open/intranet-horizontal-scaling
git clone https://gitlab.project-open.net/project-open/intranet-hr
git clone https://gitlab.project-open.net/project-open/intranet-hr-hourly-rates
git clone https://gitlab.project-open.net/project-open/intranet-icinga2
git clone https://gitlab.project-open.net/project-open/intranet-idea-management
git clone https://gitlab.project-open.net/project-open/intranet-intrusion-detection
git clone https://gitlab.project-open.net/project-open/intranet-invoices
git clone https://gitlab.project-open.net/project-open/intranet-invoices-templates
git clone https://gitlab.project-open.net/project-open/intranet-invoices-workflow
git clone https://gitlab.project-open.net/project-open/intranet-ip2nation
git clone https://gitlab.project-open.net/project-open/intranet-jira
git clone https://gitlab.project-open.net/project-open/intranet-leaflet
git clone https://gitlab.project-open.net/project-open/intranet-mail-import
git clone https://gitlab.project-open.net/project-open/intranet-material
git clone https://gitlab.project-open.net/project-open/intranet-milestone
git clone https://gitlab.project-open.net/project-open/intranet-mylyn
git clone https://gitlab.project-open.net/project-open/intranet-nagios
git clone https://gitlab.project-open.net/project-open/intranet-navision
git clone https://gitlab.project-open.net/project-open/intranet-notes
git clone https://gitlab.project-open.net/project-open/intranet-notes-tutorial
git clone https://gitlab.project-open.net/project-open/intranet-ophelia
git clone https://gitlab.project-open.net/project-open/intranet-otp
git clone https://gitlab.project-open.net/project-open/intranet-otrs-integration
git clone https://gitlab.project-open.net/project-open/intranet-overtime
git clone https://gitlab.project-open.net/project-open/intranet-payments
git clone https://gitlab.project-open.net/project-open/intranet-planning
git clone https://gitlab.project-open.net/project-open/intranet-portfolio-management
git clone https://gitlab.project-open.net/project-open/intranet-portfolio-planner
git clone https://gitlab.project-open.net/project-open/intranet-project-reminders
git clone https://gitlab.project-open.net/project-open/intranet-project-scoring
git clone https://gitlab.project-open.net/project-open/intranet-release-mgmt
git clone https://gitlab.project-open.net/project-open/intranet-reporting
git clone https://gitlab.project-open.net/project-open/intranet-reporting-cubes
git clone https://gitlab.project-open.net/project-open/intranet-reporting-dashboard
git clone https://gitlab.project-open.net/project-open/intranet-reporting-finance
git clone https://gitlab.project-open.net/project-open/intranet-reporting-indicators
git clone https://gitlab.project-open.net/project-open/intranet-reporting-openoffice
git clone https://gitlab.project-open.net/project-open/intranet-reporting-translation
git clone https://gitlab.project-open.net/project-open/intranet-reporting-tutorial
git clone https://gitlab.project-open.net/project-open/intranet-resource-management
git clone https://gitlab.project-open.net/project-open/intranet-rest
git clone https://gitlab.project-open.net/project-open/intranet-rest-fs-openacs
git clone https://gitlab.project-open.net/project-open/intranet-riskmanagement
git clone https://gitlab.project-open.net/project-open/intranet-riskmanagement-adrtel
git clone https://gitlab.project-open.net/project-open/intranet-rss-reader
git clone https://gitlab.project-open.net/project-open/intranet-rule-engine
git clone https://gitlab.project-open.net/project-open/intranet-scrum
git clone https://gitlab.project-open.net/project-open/intranet-search
git clone https://gitlab.project-open.net/project-open/intranet-search-oracle
git clone https://gitlab.project-open.net/project-open/intranet-search-pg
git clone https://gitlab.project-open.net/project-open/intranet-search-pg-files
git clone https://gitlab.project-open.net/project-open/intranet-security-static
git clone https://gitlab.project-open.net/project-open/intranet-security-update-client
git clone https://gitlab.project-open.net/project-open/intranet-security-update-server
git clone https://gitlab.project-open.net/project-open/intranet-sencha-filestorage
git clone https://gitlab.project-open.net/project-open/intranet-sharepoint
git clone https://gitlab.project-open.net/project-open/intranet-simple-survey
git clone https://gitlab.project-open.net/project-open/intranet-slack
git clone https://gitlab.project-open.net/project-open/intranet-sla-management
git clone https://gitlab.project-open.net/project-open/intranet-spam
git clone https://gitlab.project-open.net/project-open/intranet-sql-selectors
git clone https://gitlab.project-open.net/project-open/intranet-sugarcrm
git clone https://gitlab.project-open.net/project-open/intranet-sysconfig
git clone https://gitlab.project-open.net/project-open/intranet-task-management
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-interval
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-invoices
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-sencha
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-task-popup
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-tasks
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-workflow
git clone https://gitlab.project-open.net/project-open/intranet-timesheet-reminders
git clone https://gitlab.project-open.net/project-open/intranet-touch-timesheet
git clone https://gitlab.project-open.net/project-open/intranet-trans-invoice-authorization
git clone https://gitlab.project-open.net/project-open/intranet-trans-invoices
git clone https://gitlab.project-open.net/project-open/intranet-trans-invoices-moravia
git clone https://gitlab.project-open.net/project-open/intranet-trans-invoices-vaw
git clone https://gitlab.project-open.net/project-open/intranet-translation
git clone https://gitlab.project-open.net/project-open/intranet-trans-project-feedback
git clone https://gitlab.project-open.net/project-open/intranet-trans-project-wizard
git clone https://gitlab.project-open.net/project-open/intranet-trans-quality
git clone https://gitlab.project-open.net/project-open/intranet-ubl
git clone https://gitlab.project-open.net/project-open/intranet-update-server
git clone https://gitlab.project-open.net/project-open/intranet-wall
git clone https://gitlab.project-open.net/project-open/intranet-wiki
git clone https://gitlab.project-open.net/project-open/intranet-workflow
git clone https://gitlab.project-open.net/project-open/intranet-xmlrpc
git clone https://gitlab.project-open.net/project-open/lars-blogger
git clone https://gitlab.project-open.net/project-open/mail-tracking
git clone https://gitlab.project-open.net/project-open/notifications
git clone https://gitlab.project-open.net/project-open/oacs-dav
git clone https://gitlab.project-open.net/project-open/openacs-default-theme
git clone https://gitlab.project-open.net/project-open/organizations
git clone https://gitlab.project-open.net/project-open/oryx-ts-extensions
git clone https://gitlab.project-open.net/project-open/postal-address
git clone https://gitlab.project-open.net/project-open/ref-countries
git clone https://gitlab.project-open.net/project-open/ref-currency
git clone https://gitlab.project-open.net/project-open/ref-itu
git clone https://gitlab.project-open.net/project-open/ref-language
git clone https://gitlab.project-open.net/project-open/ref-timezones
git clone https://gitlab.project-open.net/project-open/ref-us-counties
git clone https://gitlab.project-open.net/project-open/ref-us-states
git clone https://gitlab.project-open.net/project-open/ref-us-zipcodes
git clone https://gitlab.project-open.net/project-open/richtext-ckeditor4
git clone https://gitlab.project-open.net/project-open/rss-support
git clone https://gitlab.project-open.net/project-open/search
git clone https://gitlab.project-open.net/project-open/sencha-core
git clone https://gitlab.project-open.net/project-open/sencha-extjs-v421
git clone https://gitlab.project-open.net/project-open/sencha-extjs-v421-dev
git clone https://gitlab.project-open.net/project-open/sencha-filestorage
git clone https://gitlab.project-open.net/project-open/sencha-member-portlet
git clone https://gitlab.project-open.net/project-open/sencha-reporting-portfolio
git clone https://gitlab.project-open.net/project-open/senchatouch-notes
git clone https://gitlab.project-open.net/project-open/senchatouch-timesheet
git clone https://gitlab.project-open.net/project-open/senchatouch-v211
git clone https://gitlab.project-open.net/project-open/senchatouch-v231a
git clone https://gitlab.project-open.net/project-open/senchatouch-v242
git clone https://gitlab.project-open.net/project-open/simple-survey
git clone https://gitlab.project-open.net/project-open/tclwebtest
git clone https://gitlab.project-open.net/project-open/telecom-number
git clone https://gitlab.project-open.net/project-open/trackback
git clone https://gitlab.project-open.net/project-open/tsearch2-driver
git clone https://gitlab.project-open.net/project-open/upgrade-3.0-3.1
git clone https://gitlab.project-open.net/project-open/upgrade-3.1-3.2
git clone https://gitlab.project-open.net/project-open/upgrade-3.2-3.3
git clone https://gitlab.project-open.net/project-open/upgrade-3.3-3.4
git clone https://gitlab.project-open.net/project-open/upgrade-3.4-3.5
git clone https://gitlab.project-open.net/project-open/upgrade-3.5-4.0
git clone https://gitlab.project-open.net/project-open/upgrade-4.0-4.1
git clone https://gitlab.project-open.net/project-open/upgrade-4.1-5.0
git clone https://gitlab.project-open.net/project-open/upgrade-5.0-5.1
git clone https://gitlab.project-open.net/project-open/wiki
git clone https://gitlab.project-open.net/project-open/workflow
git clone https://gitlab.project-open.net/project-open/xml-rpc
git clone https://gitlab.project-open.net/project-open/xotcl-core
git clone https://gitlab.project-open.net/project-open/xotcl-request-monitor
git clone https://gitlab.project-open.net/project-open/xowiki
