#!/bin/bash

git clone https://gitlab.project-open.net/project-open/acs-admin.git
git clone https://gitlab.project-open.net/project-open/acs-api-browser.git
git clone https://gitlab.project-open.net/project-open/acs-authentication.git
git clone https://gitlab.project-open.net/project-open/acs-automated-testing.git
git clone https://gitlab.project-open.net/project-open/acs-bootstrap-installer.git
git clone https://gitlab.project-open.net/project-open/acs-content-repository.git
git clone https://gitlab.project-open.net/project-open/acs-core-docs.git
git clone https://gitlab.project-open.net/project-open/acs-datetime.git
git clone https://gitlab.project-open.net/project-open/acs-developer-support.git
git clone https://gitlab.project-open.net/project-open/acs-events.git
git clone https://gitlab.project-open.net/project-open/acs-kernel.git
git clone https://gitlab.project-open.net/project-open/acs-lang.git
git clone https://gitlab.project-open.net/project-open/acs-mail.git
git clone https://gitlab.project-open.net/project-open/acs-mail-lite.git
git clone https://gitlab.project-open.net/project-open/acs-messaging.git
git clone https://gitlab.project-open.net/project-open/acs-reference.git
git clone https://gitlab.project-open.net/project-open/acs-service-contract.git
git clone https://gitlab.project-open.net/project-open/acs-subsite.git
git clone https://gitlab.project-open.net/project-open/acs-tcl.git
git clone https://gitlab.project-open.net/project-open/acs-templating.git
git clone https://gitlab.project-open.net/project-open/acs-translations.git
git clone https://gitlab.project-open.net/project-open/acs-workflow.git
git clone https://gitlab.project-open.net/project-open/ajaxhelper.git
git clone https://gitlab.project-open.net/project-open/attachments.git
git clone https://gitlab.project-open.net/project-open/calendar.git
git clone https://gitlab.project-open.net/project-open/categories.git
git clone https://gitlab.project-open.net/project-open/diagram.git
git clone https://gitlab.project-open.net/project-open/file-storage.git
git clone https://gitlab.project-open.net/project-open/general-comments.git
git clone https://gitlab.project-open.net/project-open/intranet-agile.git
git clone https://gitlab.project-open.net/project-open/intranet-calendar.git
git clone https://gitlab.project-open.net/project-open/intranet-confdb.git
git clone https://gitlab.project-open.net/project-open/intranet-core.git
git clone https://gitlab.project-open.net/project-open/intranet-cost.git
git clone https://gitlab.project-open.net/project-open/intranet-crm-opportunities.git
git clone https://gitlab.project-open.net/project-open/intranet-csv-import.git
git clone https://gitlab.project-open.net/project-open/intranet-cvs-integration.git
git clone https://gitlab.project-open.net/project-open/intranet-department-planner.git
git clone https://gitlab.project-open.net/project-open/intranet-demo-data.git
git clone https://gitlab.project-open.net/project-open/intranet-dw-light.git
git clone https://gitlab.project-open.net/project-open/intranet-dynfield.git
git clone https://gitlab.project-open.net/project-open/intranet-earned-value-management.git
git clone https://gitlab.project-open.net/project-open/intranet-exchange-rate.git
git clone https://gitlab.project-open.net/project-open/intranet-expenses.git
git clone https://gitlab.project-open.net/project-open/intranet-expenses-workflow.git
git clone https://gitlab.project-open.net/project-open/intranet-filestorage.git
git clone https://gitlab.project-open.net/project-open/intranet-forum.git
git clone https://gitlab.project-open.net/project-open/intranet-freelance.git
git clone https://gitlab.project-open.net/project-open/intranet-gantt-editor.git
git clone https://gitlab.project-open.net/project-open/intranet-ganttproject.git
git clone https://gitlab.project-open.net/project-open/intranet-helpdesk.git
git clone https://gitlab.project-open.net/project-open/intranet-hr.git
git clone https://gitlab.project-open.net/project-open/intranet-idea-management.git
git clone https://gitlab.project-open.net/project-open/intranet-invoices.git
git clone https://gitlab.project-open.net/project-open/intranet-invoices-templates.git
git clone https://gitlab.project-open.net/project-open/intranet-jira.git
git clone https://gitlab.project-open.net/project-open/intranet-mail-import.git
git clone https://gitlab.project-open.net/project-open/intranet-material.git
git clone https://gitlab.project-open.net/project-open/intranet-milestone.git
git clone https://gitlab.project-open.net/project-open/intranet-nagios.git
git clone https://gitlab.project-open.net/project-open/intranet-notes.git
git clone https://gitlab.project-open.net/project-open/intranet-payments.git
git clone https://gitlab.project-open.net/project-open/intranet-planning.git
git clone https://gitlab.project-open.net/project-open/intranet-portfolio-management.git
git clone https://gitlab.project-open.net/project-open/intranet-portfolio-planner.git
git clone https://gitlab.project-open.net/project-open/intranet-project-scoring.git
git clone https://gitlab.project-open.net/project-open/intranet-release-mgmt.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-dashboard.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-finance.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-indicators.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-openoffice.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-tutorial.git
git clone https://gitlab.project-open.net/project-open/intranet-resource-management.git
git clone https://gitlab.project-open.net/project-open/intranet-rest.git
git clone https://gitlab.project-open.net/project-open/intranet-riskmanagement.git
git clone https://gitlab.project-open.net/project-open/intranet-rule-engine.git
git clone https://gitlab.project-open.net/project-open/intranet-search-pg.git
git clone https://gitlab.project-open.net/project-open/intranet-security-update-client.git
git clone https://gitlab.project-open.net/project-open/intranet-sharepoint.git
git clone https://gitlab.project-open.net/project-open/intranet-simple-survey.git
git clone https://gitlab.project-open.net/project-open/intranet-sla-management.git
git clone https://gitlab.project-open.net/project-open/intranet-spam.git
git clone https://gitlab.project-open.net/project-open/intranet-sql-selectors.git
git clone https://gitlab.project-open.net/project-open/intranet-sugarcrm.git
git clone https://gitlab.project-open.net/project-open/intranet-sysconfig.git
git clone https://gitlab.project-open.net/project-open/intranet-task-management.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-invoices.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-task-popup.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-tasks.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-workflow.git
git clone https://gitlab.project-open.net/project-open/intranet-wiki.git
git clone https://gitlab.project-open.net/project-open/intranet-workflow.git
git clone https://gitlab.project-open.net/project-open/intranet-xmlrpc.git
git clone https://gitlab.project-open.net/project-open/mail-tracking.git
git clone https://gitlab.project-open.net/project-open/notifications.git
git clone https://gitlab.project-open.net/project-open/oacs-dav.git
git clone https://gitlab.project-open.net/project-open/openacs-default-theme.git
git clone https://gitlab.project-open.net/project-open/organizations.git
git clone https://gitlab.project-open.net/project-open/postal-address.git
git clone https://gitlab.project-open.net/project-open/ref-countries.git
git clone https://gitlab.project-open.net/project-open/ref-currency.git
git clone https://gitlab.project-open.net/project-open/ref-language.git
git clone https://gitlab.project-open.net/project-open/ref-timezones.git
git clone https://gitlab.project-open.net/project-open/ref-us-counties.git
git clone https://gitlab.project-open.net/project-open/ref-us-states.git
git clone https://gitlab.project-open.net/project-open/ref-us-zipcodes.git
git clone https://gitlab.project-open.net/project-open/rss-support.git
git clone https://gitlab.project-open.net/project-open/search.git
git clone https://gitlab.project-open.net/project-open/sencha-core.git
git clone https://gitlab.project-open.net/project-open/sencha-extjs-v421.git
git clone https://gitlab.project-open.net/project-open/senchatouch-v242.git
git clone https://gitlab.project-open.net/project-open/senchatouch-timesheet.git
git clone https://gitlab.project-open.net/project-open/simple-survey.git
git clone https://gitlab.project-open.net/project-open/tsearch2-driver.git
git clone https://gitlab.project-open.net/project-open/wiki.git
git clone https://gitlab.project-open.net/project-open/workflow.git
git clone https://gitlab.project-open.net/project-open/xml-rpc.git
git clone https://gitlab.project-open.net/project-open/xotcl-core.git
git clone https://gitlab.project-open.net/project-open/xotcl-request-monitor.git
git clone https://gitlab.project-open.net/project-open/xowiki.git
