#!/bin/bash

git clone https://gitlab.project-open.net/project-open/acs-admin.git
git clone https://gitlab.project-open.net/project-open/acs-api-browser.git
git clone https://gitlab.project-open.net/project-open/acs-authentication.git
git clone https://gitlab.project-open.net/project-open/acs-automated-testing.git
git clone https://gitlab.project-open.net/project-open/acs-bootstrap-installer.git
git clone https://gitlab.project-open.net/project-open/acs-content-repository.git
git clone https://gitlab.project-open.net/project-open/acs-core-docs.git
git clone https://gitlab.project-open.net/project-open/acs-datetime.git
git clone https://gitlab.project-open.net/project-open/acs-developer-support.git
git clone https://gitlab.project-open.net/project-open/acs-events.git
git clone https://gitlab.project-open.net/project-open/acs-kernel.git
git clone https://gitlab.project-open.net/project-open/acs-lang.git
git clone https://gitlab.project-open.net/project-open/acs-lang-server.git
git clone https://gitlab.project-open.net/project-open/acs-mail.git
git clone https://gitlab.project-open.net/project-open/acs-mail-lite.git
git clone https://gitlab.project-open.net/project-open/acs-messaging.git
git clone https://gitlab.project-open.net/project-open/acs-reference.git
git clone https://gitlab.project-open.net/project-open/acs-service-contract.git
git clone https://gitlab.project-open.net/project-open/acs-subsite.git
git clone https://gitlab.project-open.net/project-open/acs-tcl.git
git clone https://gitlab.project-open.net/project-open/acs-templating.git
git clone https://gitlab.project-open.net/project-open/acs-translations.git
git clone https://gitlab.project-open.net/project-open/acs-workflow.git
git clone https://gitlab.project-open.net/project-open/ajaxhelper.git
git clone https://gitlab.project-open.net/project-open/attachments.git
git clone https://gitlab.project-open.net/project-open/auth-ldap-adldapsearch.git
git clone https://gitlab.project-open.net/project-open/batch-importer.git
git clone https://gitlab.project-open.net/project-open/bug-tracker.git
git clone https://gitlab.project-open.net/project-open/bulk-mail.git
git clone https://gitlab.project-open.net/project-open/calendar.git
git clone https://gitlab.project-open.net/project-open/categories.git
git clone https://gitlab.project-open.net/project-open/cronjob.git
git clone https://gitlab.project-open.net/project-open/diagram.git
git clone https://gitlab.project-open.net/project-open/edit-this-page.git
git clone https://gitlab.project-open.net/project-open/events.git
git clone https://gitlab.project-open.net/project-open/faq.git
git clone https://gitlab.project-open.net/project-open/file-storage.git
git clone https://gitlab.project-open.net/project-open/general-comments.git
git clone https://gitlab.project-open.net/project-open/intermedia-driver.git
git clone https://gitlab.project-open.net/project-open/intranet-adrtel-sap.git
git clone https://gitlab.project-open.net/project-open/intranet-agile.git
git clone https://gitlab.project-open.net/project-open/intranet-amberjack.git
git clone https://gitlab.project-open.net/project-open/intranet-asus-server.git
git clone https://gitlab.project-open.net/project-open/intranet-audit.git
git clone https://gitlab.project-open.net/project-open/intranet-baseline.git
git clone https://gitlab.project-open.net/project-open/intranet-big-brother.git
git clone https://gitlab.project-open.net/project-open/intranet-budget.git
git clone https://gitlab.project-open.net/project-open/intranet-bug-tracker.git
git clone https://gitlab.project-open.net/project-open/intranet-calendar.git
git clone https://gitlab.project-open.net/project-open/intranet-calendar-holidays.git
git clone https://gitlab.project-open.net/project-open/intranet-confdb.git
git clone https://gitlab.project-open.net/project-open/intranet-contacts.git
git clone https://gitlab.project-open.net/project-open/intranet-core.git
git clone https://gitlab.project-open.net/project-open/intranet-cost.git
git clone https://gitlab.project-open.net/project-open/intranet-cost-center.git
git clone https://gitlab.project-open.net/project-open/intranet-cost-interco.git
git clone https://gitlab.project-open.net/project-open/intranet-crm-opportunities.git
git clone https://gitlab.project-open.net/project-open/intranet-crm-opportunities-adrtel.git
git clone https://gitlab.project-open.net/project-open/intranet-crm-software-comparison.git
git clone https://gitlab.project-open.net/project-open/intranet-crm-tracking.git
git clone https://gitlab.project-open.net/project-open/intranet-csv-import.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-adrtel.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-aec.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-baselkb.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-bnef.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-bubblebridge.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-bv.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-cambridge.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-celonic.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-champ.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-conti.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-cosine.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-cpdc.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-csmi.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-ctubasel.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-economedic.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-efficientip.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-eicom.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-ekelow.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-fttx.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-genedata.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-haas.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-hispano.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-infrax.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-issa.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-jago.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-koernigweber.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-kpc.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-laser.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-lexcelera.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-lippokwolf.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-moravia.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-nest.git
git clone https://gitlab.project-open.net/project-open/intranet-customer-portal.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-opi.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-processa.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-projop.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-reinisch.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-rosetta.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-santander.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-seim.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-semiotic.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-shi.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-sjm.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-solidline.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-sprylab.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-tembit.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-ventum.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-versia.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-whp.git
git clone https://gitlab.project-open.net/project-open/intranet-cust-yada.git
git clone https://gitlab.project-open.net/project-open/intranet-cvs-integration.git
git clone https://gitlab.project-open.net/project-open/intranet-demo-data.git
git clone https://gitlab.project-open.net/project-open/intranet-department-planner.git
git clone https://gitlab.project-open.net/project-open/intranet-dw-light.git
git clone https://gitlab.project-open.net/project-open/intranet-dynfield.git
git clone https://gitlab.project-open.net/project-open/intranet-earned-value-management.git
git clone https://gitlab.project-open.net/project-open/intranet-employee-evaluation.git
git clone https://gitlab.project-open.net/project-open/intranet-estimate-to-complete.git
git clone https://gitlab.project-open.net/project-open/intranet-events.git
git clone https://gitlab.project-open.net/project-open/intranet-exchange-rate.git
git clone https://gitlab.project-open.net/project-open/intranet-expenses.git
git clone https://gitlab.project-open.net/project-open/intranet-expenses-workflow.git
git clone https://gitlab.project-open.net/project-open/intranet-filestorage.git
git clone https://gitlab.project-open.net/project-open/intranet-filestorage-size-indicator.git
git clone https://gitlab.project-open.net/project-open/intranet-forum.git
git clone https://gitlab.project-open.net/project-open/intranet-freelance.git
git clone https://gitlab.project-open.net/project-open/intranet-freelance-invoices.git
git clone https://gitlab.project-open.net/project-open/intranet-freelance-invoices-moravia.git
git clone https://gitlab.project-open.net/project-open/intranet-freelance-rfqs.git
git clone https://gitlab.project-open.net/project-open/intranet-freelance-translation.git
git clone https://gitlab.project-open.net/project-open/intranet-funambol.git
git clone https://gitlab.project-open.net/project-open/intranet-gantt-editor.git
git clone https://gitlab.project-open.net/project-open/intranet-ganttproject.git
git clone https://gitlab.project-open.net/project-open/intranet-general-comments.git
git clone https://gitlab.project-open.net/project-open/intranet-gtd-dashboard.git
git clone https://gitlab.project-open.net/project-open/intranet-helpdesk.git
git clone https://gitlab.project-open.net/project-open/intranet-horizontal-scaling.git
git clone https://gitlab.project-open.net/project-open/intranet-hr.git
git clone https://gitlab.project-open.net/project-open/intranet-hr-hourly-rates.git
git clone https://gitlab.project-open.net/project-open/intranet-icinga2.git
git clone https://gitlab.project-open.net/project-open/intranet-idea-management.git
git clone https://gitlab.project-open.net/project-open/intranet-intrusion-detection.git
git clone https://gitlab.project-open.net/project-open/intranet-invoices.git
git clone https://gitlab.project-open.net/project-open/intranet-invoices-templates.git
git clone https://gitlab.project-open.net/project-open/intranet-invoices-workflow.git
git clone https://gitlab.project-open.net/project-open/intranet-ip2nation.git
git clone https://gitlab.project-open.net/project-open/intranet-jira.git
git clone https://gitlab.project-open.net/project-open/intranet-leaflet.git
git clone https://gitlab.project-open.net/project-open/intranet-mail-import.git
git clone https://gitlab.project-open.net/project-open/intranet-material.git
git clone https://gitlab.project-open.net/project-open/intranet-milestone.git
git clone https://gitlab.project-open.net/project-open/intranet-mylyn.git
git clone https://gitlab.project-open.net/project-open/intranet-nagios.git
git clone https://gitlab.project-open.net/project-open/intranet-navision.git
git clone https://gitlab.project-open.net/project-open/intranet-notes.git
git clone https://gitlab.project-open.net/project-open/intranet-notes-tutorial.git
git clone https://gitlab.project-open.net/project-open/intranet-ophelia.git
git clone https://gitlab.project-open.net/project-open/intranet-otp.git
git clone https://gitlab.project-open.net/project-open/intranet-otrs-integration.git
git clone https://gitlab.project-open.net/project-open/intranet-overtime.git
git clone https://gitlab.project-open.net/project-open/intranet-payments.git
git clone https://gitlab.project-open.net/project-open/intranet-planning.git
git clone https://gitlab.project-open.net/project-open/intranet-portfolio-management.git
git clone https://gitlab.project-open.net/project-open/intranet-portfolio-planner.git
git clone https://gitlab.project-open.net/project-open/intranet-project-reminders.git
git clone https://gitlab.project-open.net/project-open/intranet-project-scoring.git
git clone https://gitlab.project-open.net/project-open/intranet-release-mgmt.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-cubes.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-dashboard.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-finance.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-indicators.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-openoffice.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-translation.git
git clone https://gitlab.project-open.net/project-open/intranet-reporting-tutorial.git
git clone https://gitlab.project-open.net/project-open/intranet-resource-management.git
git clone https://gitlab.project-open.net/project-open/intranet-rest.git
git clone https://gitlab.project-open.net/project-open/intranet-rest-fs-openacs.git
git clone https://gitlab.project-open.net/project-open/intranet-riskmanagement.git
git clone https://gitlab.project-open.net/project-open/intranet-riskmanagement-adrtel.git
git clone https://gitlab.project-open.net/project-open/intranet-rss-reader.git
git clone https://gitlab.project-open.net/project-open/intranet-rule-engine.git
git clone https://gitlab.project-open.net/project-open/intranet-scrum.git
git clone https://gitlab.project-open.net/project-open/intranet-search.git
git clone https://gitlab.project-open.net/project-open/intranet-search-oracle.git
git clone https://gitlab.project-open.net/project-open/intranet-search-pg.git
git clone https://gitlab.project-open.net/project-open/intranet-search-pg-files.git
git clone https://gitlab.project-open.net/project-open/intranet-security-static.git
git clone https://gitlab.project-open.net/project-open/intranet-security-update-client.git
git clone https://gitlab.project-open.net/project-open/intranet-security-update-server.git
git clone https://gitlab.project-open.net/project-open/intranet-sencha-filestorage.git
git clone https://gitlab.project-open.net/project-open/intranet-sharepoint.git
git clone https://gitlab.project-open.net/project-open/intranet-simple-survey.git
git clone https://gitlab.project-open.net/project-open/intranet-slack.git
git clone https://gitlab.project-open.net/project-open/intranet-sla-management.git
git clone https://gitlab.project-open.net/project-open/intranet-spam.git
git clone https://gitlab.project-open.net/project-open/intranet-sql-selectors.git
git clone https://gitlab.project-open.net/project-open/intranet-sugarcrm.git
git clone https://gitlab.project-open.net/project-open/intranet-sysconfig.git
git clone https://gitlab.project-open.net/project-open/intranet-task-management.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-interval.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-invoices.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-sencha.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-task-popup.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-tasks.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-workflow.git
git clone https://gitlab.project-open.net/project-open/intranet-timesheet-reminders.git
git clone https://gitlab.project-open.net/project-open/intranet-touch-timesheet.git
git clone https://gitlab.project-open.net/project-open/intranet-trans-invoice-authorization.git
git clone https://gitlab.project-open.net/project-open/intranet-trans-invoices.git
git clone https://gitlab.project-open.net/project-open/intranet-trans-invoices-moravia.git
git clone https://gitlab.project-open.net/project-open/intranet-trans-invoices-vaw.git
git clone https://gitlab.project-open.net/project-open/intranet-translation.git
git clone https://gitlab.project-open.net/project-open/intranet-trans-project-feedback.git
git clone https://gitlab.project-open.net/project-open/intranet-trans-project-wizard.git
git clone https://gitlab.project-open.net/project-open/intranet-trans-quality.git
git clone https://gitlab.project-open.net/project-open/intranet-ubl.git
git clone https://gitlab.project-open.net/project-open/intranet-update-server.git
git clone https://gitlab.project-open.net/project-open/intranet-wall.git
git clone https://gitlab.project-open.net/project-open/intranet-wiki.git
git clone https://gitlab.project-open.net/project-open/intranet-workflow.git
git clone https://gitlab.project-open.net/project-open/intranet-xmlrpc.git
git clone https://gitlab.project-open.net/project-open/lars-blogger.git
git clone https://gitlab.project-open.net/project-open/mail-tracking.git
git clone https://gitlab.project-open.net/project-open/notifications.git
git clone https://gitlab.project-open.net/project-open/oacs-dav.git
git clone https://gitlab.project-open.net/project-open/openacs-default-theme.git
git clone https://gitlab.project-open.net/project-open/organizations.git
git clone https://gitlab.project-open.net/project-open/oryx-ts-extensions.git
git clone https://gitlab.project-open.net/project-open/postal-address.git
git clone https://gitlab.project-open.net/project-open/ref-countries.git
git clone https://gitlab.project-open.net/project-open/ref-currency.git
git clone https://gitlab.project-open.net/project-open/ref-itu.git
git clone https://gitlab.project-open.net/project-open/ref-language.git
git clone https://gitlab.project-open.net/project-open/ref-timezones.git
git clone https://gitlab.project-open.net/project-open/ref-us-counties.git
git clone https://gitlab.project-open.net/project-open/ref-us-states.git
git clone https://gitlab.project-open.net/project-open/ref-us-zipcodes.git
git clone https://gitlab.project-open.net/project-open/richtext-ckeditor4.git
git clone https://gitlab.project-open.net/project-open/rss-support.git
git clone https://gitlab.project-open.net/project-open/search.git
git clone https://gitlab.project-open.net/project-open/sencha-core.git
git clone https://gitlab.project-open.net/project-open/sencha-extjs-v421.git
git clone https://gitlab.project-open.net/project-open/sencha-extjs-v421-dev.git
git clone https://gitlab.project-open.net/project-open/sencha-filestorage.git
git clone https://gitlab.project-open.net/project-open/sencha-member-portlet.git
git clone https://gitlab.project-open.net/project-open/sencha-reporting-portfolio.git
git clone https://gitlab.project-open.net/project-open/senchatouch-notes.git
git clone https://gitlab.project-open.net/project-open/senchatouch-timesheet.git
git clone https://gitlab.project-open.net/project-open/senchatouch-v211.git
git clone https://gitlab.project-open.net/project-open/senchatouch-v231a.git
git clone https://gitlab.project-open.net/project-open/senchatouch-v242.git
git clone https://gitlab.project-open.net/project-open/simple-survey.git
git clone https://gitlab.project-open.net/project-open/tclwebtest.git
git clone https://gitlab.project-open.net/project-open/telecom-number.git
git clone https://gitlab.project-open.net/project-open/trackback.git
git clone https://gitlab.project-open.net/project-open/tsearch2-driver.git
git clone https://gitlab.project-open.net/project-open/upgrade-3.0-3.1.git
git clone https://gitlab.project-open.net/project-open/upgrade-3.1-3.2.git
git clone https://gitlab.project-open.net/project-open/upgrade-3.2-3.3.git
git clone https://gitlab.project-open.net/project-open/upgrade-3.3-3.4.git
git clone https://gitlab.project-open.net/project-open/upgrade-3.4-3.5.git
git clone https://gitlab.project-open.net/project-open/upgrade-3.5-4.0.git
git clone https://gitlab.project-open.net/project-open/upgrade-4.0-4.1.git
git clone https://gitlab.project-open.net/project-open/upgrade-4.1-5.0.git
git clone https://gitlab.project-open.net/project-open/upgrade-5.0-5.1.git
git clone https://gitlab.project-open.net/project-open/wiki.git
git clone https://gitlab.project-open.net/project-open/workflow.git
git clone https://gitlab.project-open.net/project-open/xml-rpc.git
git clone https://gitlab.project-open.net/project-open/xotcl-core.git
git clone https://gitlab.project-open.net/project-open/xotcl-request-monitor.git
git clone https://gitlab.project-open.net/project-open/xowiki.git
