#!/bin/bash

git clone https://gitlab.project-open.net/project-open/acs-admin
git clone https://gitlab.project-open.net/project-open/acs-api-browser
git clone https://gitlab.project-open.net/project-open/acs-authentication
git clone https://gitlab.project-open.net/project-open/acs-automated-testing
git clone https://gitlab.project-open.net/project-open/acs-bootstrap-installer
git clone https://gitlab.project-open.net/project-open/acs-content-repository
git clone https://gitlab.project-open.net/project-open/acs-core-docs
git clone https://gitlab.project-open.net/project-open/acs-datetime
git clone https://gitlab.project-open.net/project-open/acs-developer-support
git clone https://gitlab.project-open.net/project-open/acs-events
git clone https://gitlab.project-open.net/project-open/acs-kernel
git clone https://gitlab.project-open.net/project-open/acs-lang
git clone https://gitlab.project-open.net/project-open/acs-mail
git clone https://gitlab.project-open.net/project-open/acs-mail-lite
git clone https://gitlab.project-open.net/project-open/acs-messaging
git clone https://gitlab.project-open.net/project-open/acs-reference
git clone https://gitlab.project-open.net/project-open/acs-service-contract
git clone https://gitlab.project-open.net/project-open/acs-subsite
git clone https://gitlab.project-open.net/project-open/acs-tcl
git clone https://gitlab.project-open.net/project-open/acs-templating
git clone https://gitlab.project-open.net/project-open/acs-translations
git clone https://gitlab.project-open.net/project-open/acs-workflow
git clone https://gitlab.project-open.net/project-open/ajaxhelper
git clone https://gitlab.project-open.net/project-open/attachments
git clone https://gitlab.project-open.net/project-open/calendar
git clone https://gitlab.project-open.net/project-open/categories
git clone https://gitlab.project-open.net/project-open/diagram
git clone https://gitlab.project-open.net/project-open/file-storage
git clone https://gitlab.project-open.net/project-open/general-comments
git clone https://gitlab.project-open.net/project-open/intranet-agile
git clone https://gitlab.project-open.net/project-open/intranet-calendar
git clone https://gitlab.project-open.net/project-open/intranet-confdb
git clone https://gitlab.project-open.net/project-open/intranet-core
git clone https://gitlab.project-open.net/project-open/intranet-cost
git clone https://gitlab.project-open.net/project-open/intranet-crm-opportunities
git clone https://gitlab.project-open.net/project-open/intranet-csv-import
git clone https://gitlab.project-open.net/project-open/intranet-cvs-integration
git clone https://gitlab.project-open.net/project-open/intranet-department-planner
git clone https://gitlab.project-open.net/project-open/intranet-demo-data
git clone https://gitlab.project-open.net/project-open/intranet-dw-light
git clone https://gitlab.project-open.net/project-open/intranet-dynfield
git clone https://gitlab.project-open.net/project-open/intranet-earned-value-management
git clone https://gitlab.project-open.net/project-open/intranet-exchange-rate
git clone https://gitlab.project-open.net/project-open/intranet-expenses
git clone https://gitlab.project-open.net/project-open/intranet-expenses-workflow
git clone https://gitlab.project-open.net/project-open/intranet-filestorage
git clone https://gitlab.project-open.net/project-open/intranet-forum
git clone https://gitlab.project-open.net/project-open/intranet-freelance
git clone https://gitlab.project-open.net/project-open/intranet-gantt-editor
git clone https://gitlab.project-open.net/project-open/intranet-ganttproject
git clone https://gitlab.project-open.net/project-open/intranet-helpdesk
git clone https://gitlab.project-open.net/project-open/intranet-hr
git clone https://gitlab.project-open.net/project-open/intranet-idea-management
git clone https://gitlab.project-open.net/project-open/intranet-invoices
git clone https://gitlab.project-open.net/project-open/intranet-invoices-templates
git clone https://gitlab.project-open.net/project-open/intranet-jira
git clone https://gitlab.project-open.net/project-open/intranet-mail-import
git clone https://gitlab.project-open.net/project-open/intranet-material
git clone https://gitlab.project-open.net/project-open/intranet-milestone
git clone https://gitlab.project-open.net/project-open/intranet-nagios
git clone https://gitlab.project-open.net/project-open/intranet-notes
git clone https://gitlab.project-open.net/project-open/intranet-payments
git clone https://gitlab.project-open.net/project-open/intranet-planning
git clone https://gitlab.project-open.net/project-open/intranet-portfolio-management
git clone https://gitlab.project-open.net/project-open/intranet-portfolio-planner
git clone https://gitlab.project-open.net/project-open/intranet-project-scoring
git clone https://gitlab.project-open.net/project-open/intranet-release-mgmt
git clone https://gitlab.project-open.net/project-open/intranet-reporting
git clone https://gitlab.project-open.net/project-open/intranet-reporting-dashboard
git clone https://gitlab.project-open.net/project-open/intranet-reporting-finance
git clone https://gitlab.project-open.net/project-open/intranet-reporting-indicators
git clone https://gitlab.project-open.net/project-open/intranet-reporting-openoffice
git clone https://gitlab.project-open.net/project-open/intranet-reporting-tutorial
git clone https://gitlab.project-open.net/project-open/intranet-resource-management
git clone https://gitlab.project-open.net/project-open/intranet-rest
git clone https://gitlab.project-open.net/project-open/intranet-riskmanagement
git clone https://gitlab.project-open.net/project-open/intranet-rule-engine
git clone https://gitlab.project-open.net/project-open/intranet-search-pg
git clone https://gitlab.project-open.net/project-open/intranet-security-update-client
git clone https://gitlab.project-open.net/project-open/intranet-sharepoint
git clone https://gitlab.project-open.net/project-open/intranet-simple-survey
git clone https://gitlab.project-open.net/project-open/intranet-sla-management
git clone https://gitlab.project-open.net/project-open/intranet-spam
git clone https://gitlab.project-open.net/project-open/intranet-sql-selectors
git clone https://gitlab.project-open.net/project-open/intranet-sugarcrm
git clone https://gitlab.project-open.net/project-open/intranet-sysconfig
git clone https://gitlab.project-open.net/project-open/intranet-task-management
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-invoices
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-task-popup
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-tasks
git clone https://gitlab.project-open.net/project-open/intranet-timesheet2-workflow
git clone https://gitlab.project-open.net/project-open/intranet-wiki
git clone https://gitlab.project-open.net/project-open/intranet-workflow
git clone https://gitlab.project-open.net/project-open/intranet-xmlrpc
git clone https://gitlab.project-open.net/project-open/mail-tracking
git clone https://gitlab.project-open.net/project-open/notifications
git clone https://gitlab.project-open.net/project-open/oacs-dav
git clone https://gitlab.project-open.net/project-open/openacs-default-theme
git clone https://gitlab.project-open.net/project-open/organizations
git clone https://gitlab.project-open.net/project-open/postal-address
git clone https://gitlab.project-open.net/project-open/ref-countries
git clone https://gitlab.project-open.net/project-open/ref-currency
git clone https://gitlab.project-open.net/project-open/ref-language
git clone https://gitlab.project-open.net/project-open/ref-timezones
git clone https://gitlab.project-open.net/project-open/ref-us-counties
git clone https://gitlab.project-open.net/project-open/ref-us-states
git clone https://gitlab.project-open.net/project-open/ref-us-zipcodes
git clone https://gitlab.project-open.net/project-open/rss-support
git clone https://gitlab.project-open.net/project-open/search
git clone https://gitlab.project-open.net/project-open/sencha-core
git clone https://gitlab.project-open.net/project-open/sencha-extjs-v421
git clone https://gitlab.project-open.net/project-open/senchatouch-v242
git clone https://gitlab.project-open.net/project-open/senchatouch-timesheet
git clone https://gitlab.project-open.net/project-open/simple-survey
git clone https://gitlab.project-open.net/project-open/tsearch-driver
git clone https://gitlab.project-open.net/project-open/wiki
git clone https://gitlab.project-open.net/project-open/workflow
git clone https://gitlab.project-open.net/project-open/xml-rpc
git clone https://gitlab.project-open.net/project-open/xotcl-core
git clone https://gitlab.project-open.net/project-open/xotcl-request-monitor
git clone https://gitlab.project-open.net/project-open/xowiki




