#!/bin/bash

cvs checkout acs-admin
cvs checkout acs-api-browser
cvs checkout acs-authentication
cvs checkout acs-automated-testing
cvs checkout acs-bootstrap-installer
cvs checkout acs-content-repository
cvs checkout acs-core-docs
cvs checkout acs-datetime
cvs checkout acs-developer-support
cvs checkout acs-events
cvs checkout acs-kernel
cvs checkout acs-lang
cvs checkout acs-mail
cvs checkout acs-mail-lite
cvs checkout acs-messaging
cvs checkout acs-reference
cvs checkout acs-service-contract
cvs checkout acs-subsite
cvs checkout acs-tcl
cvs checkout acs-templating
cvs checkout acs-translations
cvs checkout acs-workflow
cvs checkout ajaxhelper
cvs checkout attachments
cvs checkout calendar
cvs checkout categories
cvs checkout file-storage
cvs checkout general-comments
cvs checkout intranet-agile
cvs checkout intranet-calendar
cvs checkout intranet-confdb
cvs checkout intranet-core
cvs checkout intranet-cost
cvs checkout intranet-cost-center
cvs checkout intranet-crm-opportunities
cvs checkout intranet-csv-import
cvs checkout intranet-cvs-integration
cvs checkout intranet-department-planner
cvs checkout intranet-dw-light
cvs checkout intranet-dynfield
cvs checkout intranet-earned-value-management
cvs checkout intranet-exchange-rate
cvs checkout intranet-expenses
cvs checkout intranet-expenses-workflow
cvs checkout intranet-filestorage
cvs checkout intranet-forum
cvs checkout intranet-freelance
cvs checkout intranet-gantt-editor
cvs checkout intranet-ganttproject
cvs checkout intranet-helpdesk
cvs checkout intranet-hr
cvs checkout intranet-idea-management
cvs checkout intranet-invoices
cvs checkout intranet-invoices-templates
cvs checkout intranet-jira
cvs checkout intranet-mail-import
cvs checkout intranet-material
cvs checkout intranet-milestone
cvs checkout intranet-nagios
cvs checkout intranet-notes
cvs checkout intranet-payments
cvs checkout intranet-planning
cvs checkout intranet-portfolio-management
cvs checkout intranet-portfolio-planner
cvs checkout intranet-project-scoring
cvs checkout intranet-release-mgmt
cvs checkout intranet-reporting
cvs checkout intranet-reporting-dashboard
cvs checkout intranet-reporting-finance
cvs checkout intranet-reporting-indicators
cvs checkout intranet-reporting-openoffice
cvs checkout intranet-reporting-tutorial
cvs checkout intranet-resource-management
cvs checkout intranet-rest
cvs checkout intranet-riskmanagement
cvs checkout intranet-rule-engine
cvs checkout intranet-security-update-client
cvs checkout intranet-sharepoint
cvs checkout intranet-simple-survey
cvs checkout intranet-sla-management
cvs checkout intranet-spam
cvs checkout intranet-sql-selectors
cvs checkout intranet-sugarcrm
cvs checkout intranet-sysconfig
cvs checkout intranet-task-management
cvs checkout intranet-timesheet2
cvs checkout intranet-timesheet2-invoices
cvs checkout intranet-timesheet2-task-popup
cvs checkout intranet-timesheet2-tasks
cvs checkout intranet-timesheet2-workflow
cvs checkout intranet-wiki
cvs checkout intranet-workflow
cvs checkout intranet-xmlrpc
cvs checkout mail-tracking
cvs checkout notifications
cvs checkout oacs-dav
cvs checkout openacs-default-theme
cvs checkout organizations
cvs checkout postal-address
cvs checkout ref-countries
cvs checkout ref-currency
cvs checkout ref-language
cvs checkout ref-timezones
cvs checkout ref-us-counties
cvs checkout ref-us-states
cvs checkout ref-us-zipcodes
cvs checkout sencha-core
cvs checkout sencha-extjs-v421
cvs checkout senchatouch-v242
cvs checkout simple-survey
cvs checkout wiki
cvs checkout workflow
cvs checkout xml-rpc
cvs checkout xotcl-core
cvs checkout xotcl-request-monitor
cvs checkout xowiki


